name: pull-request

on:
  pull_request:
    branches:
      - master
env:
  test_tag: ghcr.io/${{ github.repository }}:test

jobs:
  test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_GHCR_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.test_tag }}
      - run: |
          docker run --rm ${{ env.test_tag }}
